"""Strategy abstractions and structured trade signal models."""

from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Literal

import pandas as pd
from pydantic import BaseModel, Field, validator

AssetClass = Literal["STK", "ETF", "CASH", "FUT", "OPT"]
Direction = Literal["long", "short", "flat"]


class TradeSignal(BaseModel):
    """Validated signal generated by deterministic strategy code."""

    symbol: str
    asset_class: AssetClass = "STK"
    timeframe: str
    direction: Direction
    entry_price: float = Field(gt=0)
    stop_loss: float | None = Field(default=None, gt=0)
    take_profit: float | None = Field(default=None, gt=0)
    confidence_score: float = Field(ge=0, le=1)
    reason: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @validator("take_profit")
    def _target_differs_from_entry(cls, value: float | None, values: dict[str, Any]) -> float | None:
        if value is not None and "entry_price" in values and value == values["entry_price"]:
            raise ValueError("take_profit must differ from entry_price")
        return value

    @property
    def reward_risk(self) -> float | None:
        """Return absolute reward/risk ratio when stop and target are available."""

        if self.stop_loss is None or self.take_profit is None:
            return None
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk <= 0:
            return None
        return reward / risk


class BaseStrategy(ABC):
    """Base class for deterministic strategies."""

    name = "base"

    def __init__(self, symbol: str, asset_class: AssetClass = "STK", timeframe: str = "1 day") -> None:
        self.symbol = symbol
        self.asset_class = asset_class
        self.timeframe = timeframe

    @abstractmethod
    def calculate_indicators(self, data: pd.DataFrame) -> pd.DataFrame:
        """Return a copy of data with strategy indicators added."""

    @abstractmethod
    def generate_signal(self, data: pd.DataFrame) -> TradeSignal | None:
        """Generate the latest actionable signal, or None when there is no setup."""

    def get_entry(self, row: pd.Series) -> float:
        return float(row["close"])

    def get_stop_loss(self, row: pd.Series, direction: Direction) -> float | None:
        close = float(row["close"])
        atr = float(row.get("atr", close * 0.01) or close * 0.01)
        if direction == "long":
            return max(0.01, close - 1.5 * atr)
        if direction == "short":
            return close + 1.5 * atr
        return None

    def get_take_profit(self, row: pd.Series, direction: Direction) -> float | None:
        close = float(row["close"])
        atr = float(row.get("atr", close * 0.01) or close * 0.01)
        if direction == "long":
            return close + 2.5 * atr
        if direction == "short":
            return max(0.01, close - 2.5 * atr)
        return None

    def get_exit(self, data: pd.DataFrame) -> bool:
        """Return True when the latest bar signals a strategy exit."""

        return False


def average_true_range(data: pd.DataFrame, period: int = 14) -> pd.Series:
    """Calculate ATR without lookahead."""

    high_low = data["high"] - data["low"]
    high_close = (data["high"] - data["close"].shift()).abs()
    low_close = (data["low"] - data["close"].shift()).abs()
    true_range = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
    return true_range.rolling(period, min_periods=period).mean()
